version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medical_departures_db
    ports:
      - "3306:3306"
    restart: always
